title: "Open AI Agents SDK"
summary: "Python初心者からエージェントエンジニアへ。OpenAI Agents SDKを使ってエージェントを開発する方法を学ぶ。"
topics: [
  "Python",
  "エージェント",
  "AI",
  "LLM",
  "OpenAI",
]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 1-1_newprofessionagentengineer
  - 2-1_environmentsetup
  - 3-0_pythonbasics
  - 3-1_pydantic
  - 3-2_asynchronousprogramming
  - 4-1_firstagent
  - 4-2_multiturn
  - 4-3_tracing
  - 4-4_structuredoutput
  - 5-1_tools
  - 5-2_websearchtool
  - 5-3_agentsastools
  - 5-4_modelcontextprotocol
  - 6-1_agenticrag
